namespace: argocd
namePrefix: prod-
nameSuffix: -nginx

resources:
  - ../../../base

patches:
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: nginx
                image: nginx:1.27  # Correctly placed inside the container spec
